### PR TITLE
Support Basic Authentication when generating access token

### PR DESCRIPTION
**Pull request by FeNoMeNa**
OAuth spec [rfc6749](https://tools.ietf.org/html/rfc6749) says that:

```
The authorization server MUST support the HTTP Basic
   authentication scheme for authenticating clients that were issued a
   client password.

   For example (with extra line breaks for display purposes only):

     Authorization: Basic czZCaGRSa3F0Mzo3RmpmcDBaQnIxS3REUmJuZlZkbUl3

   Alternatively, the authorization server MAY support including the
   client credentials in the request-body using the following
   parameters:

   client_id
         REQUIRED.  The client identifier issued to the client during
         the registration process described by Section 2.2.

   client_secret
         REQUIRED.  The client secret.  The client MAY omit the
         parameter if the client secret is an empty string.
```

### CODE REVIEW

**Comment by mlesikov** [comment]
Looking good to me.
After the merge, I will update the jar in the  TNG BSS lib

**Comment by FeNoMeNa** [comment]
Done

**Comment by mlesikov** [comment]
ok, tomorrow morning, the changes will be active

**Comment by mlesikov** [comment]
oauth authorisation now works as expected

**Comment by FeNoMeNa** [comment]
Good.

**Pull request merged**
